### PR TITLE
Add 'FHIR Core Concepts and Best Practices' slides and Postman collection from CHC 2018

### PR DESCRIPTION
**Pull request by MaxPhilips**

### CODE REVIEW

**Review by Aditya-Viswanadha — APPROVED** [review]

**Comment by dennispatterson** [comment]
Thoughts on removing the date from the file names and just replacing the old content?

**Comment by MaxPhilips** [comment]
I've updated these slides since I got them - I changed the Exercise slides (originally for attendees to work through themselves) to Examples (that I as a presenter demonstrated). I also cut most post-exercise / 'answer' slides and instead talked through that content during the demo sections

I thought we may want to preserve both styles it has been run as

**Comment by cerbs-of-yore** [comment]
The previous slides will still be available in the commit history

**Comment by MaxPhilips** [comment]
I updated the naming for the most recent presentation/postman collection, and I deleted both older versions of its slide deck with 18baeb1

**Review by dennispatterson — APPROVED** [review]

**Pull request merged**
